FROM node:latest as build-stage
WORKDIR /app/LinguaTrash
COPY ./vue/package*.json ./
RUN npm ci
COPY ./vue .
RUN npm run build


FROM nginx:1.24 as production-stage
COPY --from=build-stage ./app/LinguaTrash/dist* /app/LinguaTrash
COPY ./deploy/nginx /etc/nginx/conf.d
