FROM node:latest as build-stage
ENV NODE_OPTIONS=--openssl-legacy-provider
WORKDIR /app/LinguaTrash
COPY ./vue/package*.json ./
RUN npm ci
COPY ./vue .
RUN npm run build


FROM nginx:1.24 as production-stage
COPY --from=build-stage ./app/LinguaTrash/dist /app/LinguaTrash
COPY nginx.conf /etc/nginx/nginx.conf
