version: "3.9"

networks:
  net_nginx:
    driver: bridge
  net_db:
    driver: bridge

services:
  db:
    container_name: prod-postgres
    image: postgres:15
    restart: always
    expose:
      - 5432
    volumes:
      - pg_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
    networks:
      - net_db

  django:
    container_name: prod-django
    image: ${DOCKER_USERNAME}/${DOCKER_NAME_DJANGO}:main
    command: gunicorn main.wsgi:application --bind 0.0.0.0:8000
    networks:
      - net_db
      - net_nginx
    depends_on:
      - db

  nginx:
    container_name: prod-nginx
    image: ${DOCKER_USERNAME}/${DOCKER_NAME_NGINX}:main
    ports:
      - "8000:80"
    volumes:
      - ./deploy/nginx:/etc/nginx/conf.d
      - static:/app/LinguaTrash/static
      - media:/app/LinguaTrash/media
    networks:
      - net_nginx
    depends_on:
      - django


volumes:
  pg_data:
  static:
  media:
