# Generated by Django 4.2.7 on 2023-11-26 20:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("additional", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="holiday",
            name="day_id",
        ),
        migrations.AddField(
            model_name="holiday",
            name="day",
            field=models.DateField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name="DayOfWeek",
        ),
    ]
