# Generated by Django 3.1.5 on 2021-01-12 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocabulary', '0003_auto_20210111_1937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vocabulary',
            name='create_time',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='vocabulary',
            name='write_time',
            field=models.DateField(auto_now=True),
        ),
    ]
