# Generated by Django 3.1.5 on 2021-01-13 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vocabulary', '0008_auto_20210112_1549'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='words',
            name='word_trans',
        ),
        migrations.AlterField(
            model_name='vocabulary',
            name='name',
            field=models.CharField(max_length=2048),
        ),
        migrations.AlterField(
            model_name='words',
            name='vocabulary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vocabulary', to='vocabulary.vocabulary'),
        ),
        migrations.AlterField(
            model_name='words',
            name='word',
            field=models.CharField(max_length=2048),
        ),
        migrations.CreateModel(
            name='Translation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('translate', models.CharField(max_length=2048)),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='word_realate', to='vocabulary.words')),
            ],
        ),
    ]
