# Generated by Django 3.1.5 on 2021-02-01 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vocabulary', '0010_auto_20210201_0056'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vocabulary',
            options={'ordering': ['-like', '-id']},
        ),
    ]
