# Generated by Django 3.1.5 on 2021-02-02 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('vocabulary', '0011_auto_20210201_2333'),
    ]

    operations = [
        migrations.AddField(
            model_name='vocabulary',
            name='partner',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, related_name='partner', to='accounts.partner'),
            preserve_default=False,
        ),
    ]
