# Generated by Django 3.1.5 on 2021-02-09 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vocabulary', '0013_feedback'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='translate',
            new_name='text',
        ),
    ]
