name: Deploy

on:
  workflow_run:
    workflows: [ Django Tests ]
    types: [ completed ]

jobs:
  docker_hub:
    name: Docker Hub
    runs-on: ubuntu-latest
    env:
      USERNAME: ${{ secrets.DOCKER_USERNAME }}
      NAME_DJANGO: ${{ secrets.DOCKER_NAME_DJANGO }}
      NAME_NGINX: ${{ secrets.DOCKER_NAME_NGINX }}
      TOKEN: ${{ secrets.DOCKER_TOKEN }}
    steps:
      - uses: actions/checkout@main
      - name: Log in to Docker Hub
        run: echo $TOKEN | docker login -u $USERNAME --password-stdin
      - name: Build Django image
        run: docker build -t $USERNAME/$NAME_DJANGO:${GITHUB_REF:11} -f ./deploy/Dockerfile-Django .
      - name: Build Nginx image
        run: docker build -t $USERNAME/$NAME_NGINX:${GITHUB_REF:11} -f ./deploy/Dockerfile-Nginx .
      - name: Push Django image to Docker Hub
        run: docker push $USERNAME/$NAME_DJANGO:${GITHUB_REF:11}
      - name: Push Nginx image to Docker Hub
        run: docker push $USERNAME/$NAME_NGINX:${GITHUB_REF:11}

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: docker_hub
    steps:
      - uses: actions/checkout@main
      - name: Copy docker-compose-deploy.yml
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          source: "./deploy/docker-compose-deploy.yml"
          target: "LinguaTrash"
      - name: Docker pull & reload
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            cd LinguaTrash
            docker compose -f ./deploy/docker-compose-deploy.yml --env-file=.env pull
            docker compose -f ./deploy/docker-compose-deploy.yml --env-file=.env down
            docker compose -f ./deploy/docker-compose-deploy.yml --env-file=.env up -d
            docker compose -f ./deploy/docker-compose-deploy.yml --env-file=.env exec django python manage.py migrate
            docker compose -f ./deploy/docker-compose-deploy.yml --env-file=.env exec django python manage.py collectstatic --no-input
