name: Django Tests

on:
  push:
    branches:
      - master

jobs:
  run_tests:
    runs-on: [ubuntu-latest]

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_DATABASE: test
          POSTGRES_USER: test_user
        ports: [ "5432:5432" ]

    steps:
      - uses: actions/checkout@master
      - uses: actions/setuo-python@v1
        with:
          python-version: 3.9
          architecture: "x64"
      - name: Install requirements
        run: pip install -r requirements.txt
      - name: Tests
        run: python manage.py test
        env:
          DB_NAME: test
          DB_USER: test_user
          DB_PASSWORD: postgres
          DB_PORT: 5432
          DB_HOST: localhost
