name: Django Tests

on:
  push:
    branches: [main]

jobs:
  run_tests:
    runs-on: [ubuntu-latest]

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_DB: test_db
          POSTGRES_USER: user
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5


    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-python@v1
        with:
          python-version: 3.11.6
      - name: Install requirements
        run: pip install -r requirements.txt
      - name: Tests
        run: python manage.py test
        env:
          DB_NAME: test_db
          DB_USER: user
          DB_PASS: postgres
          DB_PORT: 5432
          DB_HOST: 127.0.0.1
