name: Django Tests

on:
  push:
    branches: [main]

jobs:
  tests:
    runs-on: [ubuntu-latest]
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_DB: test_db
          POSTGRES_USER: user
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-python@v1
        with:
          python-version: 3.11.6
      - name: Install requirements
        run: pip install -r requirements.txt
      - name: Tests
        run: python manage.py test
        env:
          DEBUG: False
          SECRET_KEY: super_secret_key
          DB_NAME: test_db
          DB_USER: user
          DB_PASS: postgres
          DB_PORT: 5432
          DB_HOST: 127.0.0.1

  docker_hub:
    name: Docker Hub
    runs-on: ubuntu-latest
    needs: tests
    env:
      USERNAME: ${{ secrets.DOCKER_USERNAME }}
      NAME_DJANGO: ${{ secrets.DOCKER_NAME_DJANGO }}
      NAME_NGINX: ${{ secrets.DOCKER_NAME_NGINX }}
      TOKEN: ${{ secrets.DOCKER_TOKEN }}
    steps:
      - uses: actions/checkout@main
      - name: Log in to Docker Hub
        run: echo $TOKEN | docker login -u $USERNAME --password-stdin
      - name: Create directories
        run: mkdir django && mkdir nginx
      - name: Build Django image
        working-directory: ./django
        run: docker build -t $USERNAME/$NAME_DJANGO:${GITHUB_REF:11} -f ../deploy/Dockerfile-Django .
      - name: Push Django image to Docker Hub
        working-directory: ./django
        run: docker push $USERNAME/$NAME_DJANGO:${GITHUB_REF:11}
      - name: Build Nginx image
        working-directory: ./nginx
        run: docker build -t $USERNAME/$NAME_NGINX:${GITHUB_REF:11} -f ../deploy/Dockerfile-Nginx .
      - name: Push Nginx image to Docker Hub
        working-directory: ./nginx
        run: docker push $USERNAME/$NAME_NGINX:${GITHUB_REF:11}
