name: Django Tests

on:
  push:
    branches: [main]

jobs:
  tests:
    runs-on: [ubuntu-latest]

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_DB: test_db
          POSTGRES_USER: user
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5


    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-python@v1
        with:
          python-version: 3.11.6
      - name: Install requirements
        run: pip install -r requirements.txt
      - name: Tests
        run: python manage.py test
        env:
          DEBUG: False
          SECRET_KEY: super_secret_key
          DB_NAME: test_db
          DB_USER: user
          DB_PASS: postgres
          DB_PORT: 5432
          DB_HOST: 127.0.0.1

  docker_hub_django:
    name: Docker Hub DJANGO
    runs-on: ubuntu-latest
    needs: tests
    env:
      USERNAME: ${{ secrets.DOCKER_USERNAME }}
      NAME: ${{ secrets.DOCKER_NAME_DJANGO }}
      TOKEN: ${{ secrets.DOCKER_TOKEN }}
    steps:
      - uses: actions/checkout@main
      - name: Log in to Docker Hub
        run: echo $TOKEN | docker login -u $USERNAME --password-stdin
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Build image
        run: docker build -t $USERNAME/$NAME:${GITHUB_REF:11} -f ./deploy/Dockerfile-Django .
      - name: Push image to Docker Hub
        run: docker push $USERNAME/$NAME:{GITHUB_REF:11}
